version: '3.8'

services:
  next-app:
    image: dimpap/webhook-server:latest
    container_name: webhook-server-container
    ports:
      - '9000:3333'
    environment:
      - NODE_ENV=production
      - WEBHOOK_SECRET= ${WEBHOOK_SECRET}
      - DEPLOYMENT_PATH=${DEPLOYMENT_PATH}
      
# In order to build the image you need to `nx build webhook-server`