version: '3.8'

services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault_container
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
    ports:
      - '8200:8200'
    environment:
      VAULT_ADDR: 'http://0.0.0.0:8200'
    volumes:
      - ./config:/vault/config
      - ./data:/vault/file
    command: vault server -config=/vault/config/vault.hcl
