version: '3.8'

services:
  next-app:
    build:
      context: .
      dockerfile: apps/next-app/Dockerfile
    image: my-next-app:latest
    container_name: next-app-container
    ports:
      - '3000:3000'

  webhook:
    build:
      context: .
      dockerfile: apps/webhook-server/Dockerfile
    image: =webhook-server:latest
    container_name: webhook-server-container
    ports:
      - '3333:3333'

# In order to build the image you need to `nx build next-app` and `nx build webhook-server`