services:
  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - '80:80'
      - '443:443'
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost/']
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/ssl/myapp/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/ssl/myapp/key.pem:/etc/ssl/private/key.pem:ro

networks:
  super-network:
    external: true
