version: '3.8'

services:
  my-api:
    image: dimpap/my-api:latest
    container_name: my-api_container
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - super-network
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3333/api/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    command: >
      sh -c "npx prisma migrate deploy --schema=./prisma/schema && node main.js"
    depends_on:
      - redis
      - postgres

  next-app:
    image: dimpap/next-app:latest
    container_name: next-app_container
    env_file:
      - .env
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - super-network

networks:
  super-network:
    external: true
