server:
  http_listen_port: 9080 # HTTP port to expose Promtail's metrics
  grpc_listen_port: 0 # Disable gRPC

positions:
  filename: /tmp/positions.yaml # File to store file offsets (so logs don't get re-scraped)

clients:
  - url: http://loki:3100/loki/api/v1/push # Loki endpoint

scrape_configs:
  - job_name: containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: container_name
    pipeline_stages:
      - json:
          expressions:
            log: log
            stream: stream
            time: time
      - labels:
          container_name:
      - output:
          source: log
      - template:
          source: log
          template: '[{{ .container_name }}] {{ .log }}'
