version: '3.8'

services:
  my-api:
    image: dimpap/my-api:latest
    container_name: my-api-container
    ports:
      - '3333:3333'
    env_file:
      - .env.test
    restart: always
    volumes:
      - ./logs:/usr/src/app/logs
    networks:
      - my-api
    command: >
      sh -c "npx prisma generate --schema=./prisma/schema && node main.js"

networks:
  my-api:
    name: test_network
