version: '3.8'

services:
  next-app:
    image: dimpap/next-app:latest
    container_name: next-app-container
    ports:
      - '3000:3000'
    env_file:
      - .env
    restart: always
    networks:
      - next-app

networks:
  next-app:
    name: postgres_network
