import MainTemplate from '../components/main.template'
import './global.css'

export const metadata = {
  title: 'Welcome',
  description: 'Generated by Dp',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-100svh bg-primary">
        <MainTemplate>{children}</MainTemplate>
      </body>
    </html>
  )
}
