services:
  postgres:
    image: postgres:16.1-alpine3.19
    container_name: postgres_container
    # ports:
    #   - '5432:5432'
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DATABASE_USER} -d ${DATABASE_DB}']
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - super-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c shared_preload_libraries=pg_stat_statements

volumes:
  postgres_data:

networks:
  super-network:
    external: true
