version: '3.8'

services:
  postgres:
    image: postgres:16.1-alpine3.19
    container_name: postgres_container
    environment:
      POSTGRES_DB: ${AUTH_DATABASE_DB}
      POSTGRES_USER: ${AUTH_DATABASE_USER}
      POSTGRES_PASSWORD: ${AUTH_DATABASE_PASSWORD}
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - postgres
    volumes:
      - ${POSTGRES_VOLUME_PATH}:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: my_adminer
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      - postgres
    depends_on:
      - postgres

networks:
  postgres:
    name: postgres_network
