#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Precommit Triggered..."

# Run Prettier to format files
# echo "Run Prettier to format files"
# npx prettier --write .

echo "Run Lint to all files"
npm run lint:all