name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - uses: nrwl/nx-set-shas@v3
      - run: npm ci

      - run: npx nx format:check

      - name: Lint check
        run: npx nx affected:lint --all

      - name: Run Tests
        run: npm test

      - name: Build Next.js App
        run: npm run build:next-app
